# Database configuration
spring.datasource.url=jdbc:mariadb://${DB_url}:${DB_port}/${DB_dataBaseName}
spring.datasource.username=${DB_name}
spring.datasource.password=${DB_password}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# MyBatis configuration
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.lotto.insight.dto

# Server JSP configuration
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# 초 기반
server.servlet.session.timeout=1800
